blank_issues_enabled: true

contact_links:
  - name: GitHub Discussions
    url: https://github.com/open-ani/ani/discussions
    about: 欢迎进行相对比较正式的讨论
  - name: QQ 闲聊群 1019689427
    url: https://qm.qq.com/q/aejkhhG5tm
    about: 欢迎反馈问题与闲聊
  - name: Telegram 闲聊群
    url: https://t.me/+afDaMsCSIcsyNDVk
    about: 欢迎反馈问题与闲聊
