target 'Animeko' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'application', :path => '../shared/application'

  pod 'Sentry', '~> 8.49.0'
  pod 'FirebaseCore', '~> 12.4.0'
  pod 'FirebaseAnalytics', '~> 12.4.0'
end
